export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#0040e0",
        "surface": "#faf8ff",
        "on-surface": "#191b24",
        "on-surface-variant": "#434656",
        "secondary": "#006d42",
        "tertiary": "#ac061b",
        "error": "#ba1a1a",
        "outline": "#747688",
        "outline-variant": "#c4c5d9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f2ff",
        "surface-container": "#ededfa",
        "surface-container-high": "#e7e7f4",
        "surface-container-highest": "#e1e1ef",
        "surface-dim": "#d9d9e6",
        "surface-variant": "#e1e1ef",
        "surface-bright": "#faf8ff",
        "primary-container": "#2e5bff",
        "primary-fixed": "#dde1ff",
        "primary-fixed-dim": "#b8c3ff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001356",
        "on-primary-fixed-variant": "#0035be",
        "secondary-container": "#62feaf",
        "secondary-fixed": "#62feaf",
        "secondary-fixed-dim": "#3ee095",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#007347",
        "on-secondary-fixed": "#002111",
        "on-secondary-fixed-variant": "#005231",
        "tertiary-container": "#d02a30",
        "tertiary-fixed": "#ffdad7",
        "tertiary-fixed-dim": "#ffb3ae",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffecea",
        "on-tertiary-fixed": "#410004",
        "on-tertiary-fixed-variant": "#930014",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e303a",
        "inverse-on-surface": "#f0f0fd",
        "inverse-primary": "#b8c3ff",
        "background": "#faf8ff",
        "on-background": "#191b24",
        "surface-tint": "#124af0",
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
    },
  },
}
